name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure your branch name is correct

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."  # Path to your site folder (change if needed)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # ✅ Updated to v3
