name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]   # 🔧 changed from main to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Site Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # This means root folder. Should contain index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
